### ISSUE TITLE
TypeError: argument should be integer or bytes-like object, not 'str'

### ISSUE THREAD

**Issue by LoulouChabChab** [cheeky4n6monkey/4n6-scripts#6]
When I try to execute imgcache-parse-mod.py or imgcache-parse.py I have this issue : 

E:\404\Test\4n6-scripts-master\4n6-scripts-master\Android>python imgcache-parse-mod.py -f 86546165715873655.0 -o output.html -p
Running imgcache-parse-mod.py v2016-08-03

Traceback (most recent call last):
  File "E:\404\Test\4n6-scripts-master\4n6-scripts-master\Android\imgcache-parse-mod.py", line 126, in <module>
    hits = all_indices(filestring, substring1, [])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\404\Test\4n6-scripts-master\4n6-scripts-master\Android\imgcache-parse-mod.py", line 66, in all_indices
    i = bigstring.find(substring, offset)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument should be integer or bytes-like object, not 'str'
 
Any idea ?

**Comment by cheeky4n6monkey** [comment]
The imgcache script was written for/tested with Python2.
Please try executing it with Python 2 instead of Python 3.
